language: kotlin
sudo: required
dist: trusty

jdk:
  - oraclejdk8

script:
  - ./gradlew clean build :kategory-docs:runAnk
  - ./gradlew codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  on:
    branch: master
    tags: true
    condition: "$TRAVIS_TAG =~ ^Release.*$"
  provider: script
  script: ./gradlew bintrayUpload