language: kotlin
sudo: required
dist: trusty

jdk:
  - oraclejdk8

script:
  - ./gradlew clean build
  - ./gradlew dokka :arrow-docs:runAnk
 
after_success:
  - ./gradlew codeCoverageReport
  - bash <(curl -s https://codecov.io/bash)
  - ./deploy-scripts/deploy.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: modules/docs/arrow-docs/build/site
  on:
    branch: master
