name: "arrow-integrations: build"

on: pull_request

jobs:
  arrow-integrations-build:

    env:
      BASEDIR: ${{github.workspace}}
      JAVA_OPTS: -Xms512m -Xmx1024m

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        architecture: x64
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Checkout orchestrator
      run: git clone https://github.com/arrow-kt/arrow.git arrow
    - name: Build with Gradle
      run: ./arrow/scripts/project-build.sh
