name: "arrow-integrations: build documentation"

on: pull_request

jobs:
  arrow-integrations_build_documentation:

    env:
      BASEDIR: ${{github.workspace}}/..
      JAVA_OPTS: -Xms512m -Xmx1024m

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        architecture: x64
    - name: Generate API doc and validate
      run: ./gradlew buildArrowDoc
