name: "Check Build Integration"

on:
  push:
    branches:
    - master

jobs:
  check-build-integration:

    env:
      BASEDIR: ${{github.workspace}}/..
      JAVA_OPTS: -Xms512m -Xmx1024m

    runs-on: macos-latest
    timeout-minutes: 90

    steps:
    - uses: actions/checkout@v2
    - name: Checkout orchestrator
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git clone https://github.com/arrow-kt/arrow.git $BASEDIR/arrow --depth 1 --no-single-branch
        . $BASEDIR/arrow/scripts/commons4gradle.sh
        updateOrchestrator master
    - name: Check Build Integration
      run: |
        $BASEDIR/arrow/scripts/check-build-integration.sh
    - name: Prepare environment to create the issue (new package)
      if: failure()
      id: create-issue
      run: |
        $BASEDIR/arrow/scripts/issue-create-description.sh > issue.log
        echo ::set-output name=title::$(git log -1 --pretty=format:%s | sed 's/"//g')
        SCRIPT_DIR=$(find $HOME -name github-script | head -n1)
        NODE_MODULES=$(find $SCRIPT_DIR -maxdepth 2 -name node_modules | head -n1)
        cd $NODE_MODULES/..
        rm -rf node_modules
        npm install
        npm install xmlhttprequest
    - name: Create the issue
      if: failure()
      uses: actions/github-script@0.3.0
      with:
        github-token: ${{github.token}}
        script: |
          var XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;
          function readFile(file) {
            var content;
            var rawFile = new XMLHttpRequest();
            rawFile.open("GET", file, false);
            rawFile.onreadystatechange = function () {
                content = rawFile.responseText;
            }
            rawFile.send();
            return content;
          }
          await github.issues.create({...context.repo,
            title: "BUILD: error when integrating '${{ steps.create-issue.outputs.title }}' with the rest of Arrow libraries",
            body: readFile("file://${{github.workspace}}/issue.log")});
