name: "arrow-integrations: publish in OSS"

on:
  push:
    branches:
    - release/0.11.0

jobs:
  arrow-integrations_publish:

    env:
      BASEDIR: ${{github.workspace}}/..
      JAVA_OPTS: -Xms512m -Xmx1024m

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        architecture: x64
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Checkout orchestrator
      run: |
        cd $BASEDIR
        git clone -b release/0.11.0 https://github.com/arrow-kt/arrow.git
    - name: Build with Gradle
      run: $BASEDIR/arrow/scripts/project-build.sh arrow-integrations
    - name: Publish artifacts
      env:
        BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
        BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
      run: $BASEDIR/arrow/scripts/project-publish.sh arrow-integrations
    - name: Prepare environment to create the issue (new package)
      if: failure()
      id: create-issue
      run: |
        echo $(git log -1 --pretty=format:%s)
        echo ::set-output name=title::$(git log -1 --pretty=format:%s)
        echo -e "## Details\n" > issue.log
        echo -e "* **Commit hash**: \`$(git log -1 --pretty=format:%h)\`\n" >> issue.log
        echo -e "* **Author**: $(git log -1 --pretty=format:%an)\n" >> issue.log
        echo -e "* **Committer**: $(git log -1 --pretty=format:%cn)\n" >> issue.log
        echo -e "* **More info**: [error log](https://github.com/arrow-kt/arrow-integrations/commit/$GITHUB_SHA/checks)\n" >> issue.log
        cat issue.log
        rm -rf /home/runner/work/_actions/actions/github-script/0.3.0/node_modules
        cd /home/runner/work/_actions/actions/github-script/0.3.0/
        npm install
        npm install xmlhttprequest
    - name: Create the issue
      if: failure()
      uses: actions/github-script@0.3.0
      with:
        github-token: ${{github.token}}
        script: |
          var XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;
          function readFile(file) {
            var content;
            var rawFile = new XMLHttpRequest();
            rawFile.open("GET", file, false);
            rawFile.onreadystatechange = function () {
                content = rawFile.responseText;
            }
            rawFile.send();
            return content;
          }
          await github.issues.create({...context.repo,
            title: "BUILD: error when merging '${{ steps.create-issue.outputs.title }}' on release/0.11.0 branch",
            body: readFile("file://${{github.workspace}}/issue.log")});
