name: "arrow-integrations: publish documentation"

on:
  push:
    branches:
    - master

jobs:
  arrow-integrations_publish_documentation:

    env:
      BASEDIR: ${{github.workspace}}/..
      JAVA_OPTS: -Xms512m -Xmx1024m

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        architecture: x64
    - name: Checkout orchestrator
      run: |
        cd $BASEDIR
        git clone https://github.com/arrow-kt/arrow.git
    - name: Run Ank for site
      run: |
        $BASEDIR/arrow/scripts/site-download.sh
        $BASEDIR/arrow/scripts/site-run-ank.sh
    - name: Generate API doc and validate
      run: ./gradlew buildArrowDoc
    - name: Join docs to site
      run: $BASEDIR/arrow/scripts/project-locate-doc.sh arrow-integrations
    - name: Prepare environment
      run: |
        $BASEDIR/arrow/scripts/site-prepare-env.sh
        $BASEDIR/arrow/scripts/install-aws.sh
    - name: Build site
      run: $BASEDIR/arrow/scripts/site-build.sh
    - name: Deploy
      env:
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_CLOUDFRONT_ID: ${{ secrets.AWS_CLOUDFRONT_ID }}
      run: $BASEDIR/arrow/scripts/site-publish.sh
    - name: Prepare environment to create the issue (new package)
      if: failure()
      id: create-issue
      run: |
        $BASEDIR/arrow/scripts/issue-create-description.sh > issue.log
        echo ::set-output name=title::$(git log -1 --pretty=format:%s)
        rm -rf /home/runner/work/_actions/actions/github-script/0.3.0/node_modules
        cd /home/runner/work/_actions/actions/github-script/0.3.0/
        npm install
        npm install xmlhttprequest
    - name: Create the issue
      if: failure()
      uses: actions/github-script@0.3.0
      with:
        github-token: ${{github.token}}
        script: |
          var XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;
          function readFile(file) {
            var content;
            var rawFile = new XMLHttpRequest();
            rawFile.open("GET", file, false);
            rawFile.onreadystatechange = function () {
                content = rawFile.responseText;
            }
            rawFile.send();
            return content;
          }
          await github.issues.create({...context.repo,
            title: "DOC: error when merging '${{ steps.create-issue.outputs.title }}' on master branch",
            body: readFile("file://${{github.workspace}}/issue.log")});
    - name: Save content
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
        AWS_CLOUDFRONT_ID: ${{ secrets.AWS_CLOUDFRONT_ID }}
      run: aws s3 ls s3://$S3_BUCKET --recursive --summarize > site-content.log
    - uses: actions/upload-artifact@v1
      with:
        name: site-content
        path: site-content.log
