version: 2

jobs:
  build:
    working_directory: ~/arrow
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      JVM_OPTS: -Xmx4g
    steps:
      - checkout
      - run:
          name: Build and Docs
          command: ./gradlew clean dokka :arrow-docs:runAnk
