name: "arrow-ank: build documentation"

on:
  pull_request:
    branches-ignore:
    - release/0.11.0

jobs:
  arrow-ank_build_documentation:

    env:
      BASEDIR: ${{github.workspace}}
      JAVA_OPTS: -Xms512m -Xmx1024m

    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        architecture: x64
    - name: Checkout orchestrator
      run: git clone https://github.com/arrow-kt/arrow.git
    - name: Run Ank for site
      run:  |
        ./arrow/scripts/site-download.sh
        ./arrow/scripts/site-run-ank.sh
    - name: Run Dokka for arrow-ank
      run: |
        git clone https://github.com/arrow-kt/arrow-ank.git
        ./arrow/scripts/project-run-dokka.sh arrow-ank
    - name: Run Ank for arrow-ank
      run: ./arrow/scripts/project-run-ank.sh arrow-ank
    - name: Join docs to site
      run: ./arrow/scripts/project-locate-doc.sh arrow-ank
    - name: Prepare environment
      run: ./arrow/scripts/site-prepare-env.sh
    - name: Build site
      run: ./arrow/scripts/site-build.sh
