name: Build Documentation

on: pull_request

jobs:
  build_documentation:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        architecture: x64
    - name: Dokka
      env:
        JAVA_OPTS: -Xms512m -Xmx1024m
      run: |
        set -ex
        ./gradlew dokka
    - name: Run Ank
      env:
        JAVA_OPTS: -Xms512m -Xmx1024m
      run: |
        set -ex
        ./gradlew :arrow-docs:runAnk
