name: "Build libraries"

on: pull_request

jobs:
  build:

    env:
      BASEDIR: ${{github.workspace}}/arrow-libs
      JAVA_OPTS: -Xms512m -Xmx1024m

    runs-on: macos-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: "Setup"
      run: brew install grep
    - name: "Set env"
      run: ${GITHUB_WORKSPACE}/.github/scripts/set-env.sh
    - name: "Show env"
      run: ${GITHUB_WORKSPACE}/.github/scripts/show-env.sh
    - name: "Build Core libraries"
      working-directory: arrow-libs/core
      run: ./gradlew build
    - name: "Build Fx libraries"
      working-directory: arrow-libs/fx
      run: ./gradlew build
    - name: "Build Optics libraries"
      working-directory: arrow-libs/optics
      run: ./gradlew build
    - name: "Build Ank library and plugin"
      working-directory: arrow-libs/ank
      run: ./gradlew build
