name: "Check Doc Integration"

on:
  pull_request:
    paths-ignore:
    - 'docs/**'
    - 'templates/**'
    - '**.md'

jobs:
  check-doc-integration:

    env:
      BASEDIR: ${{github.workspace}}/..
      JAVA_OPTS: -Xms512m -Xmx1024m

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Prepare env
      run: brew install hub
    - name: Check Doc Integration
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        BRANCH_NAME=$(echo $GITHUB_REF | cut -d/ -f3)
        ./scripts/check-doc-integration.sh $BRANCH_NAME
