name: "Publish Arrow Stack (BOM file)"

on:
  push:
    branches:
    - master
    paths:
    - 'arrow-stack/**'

jobs:
  publish-arrow-stack:

    env:
      BASEDIR: ${{github.workspace}}/arrow-libs
      BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
      BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}

    runs-on: macos-latest
    defaults:
      run:
        working-directory: arrow-stack

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: "Check versions"
      id: versions
      run: |
        LATEST_PUBLISHED_RELEASE_VERSION=$(curl -X GET https://api.bintray.com/packages/arrow-kt/arrow-kt/arrow/versions/_latest | jq -r '.name')
        RELEASE_VERSION=$(grep LATEST_VERSION $BASEDIR/gradle.properties | cut -d= -f2)
        NEW_RELEASE_VERSION_EXISTS=$([ "$LATEST_PUBLISHED_RELEASE_VERSION" == "$RELEASE_VERSION" ] && echo '0' || echo '1')
        echo "::set-output name=release-version::$RELEASE_VERSION"
        echo "::set-output name=new-release-version-exists::$NEW_RELEASE_VERSION_EXISTS"
    - name: "Update version when release"
      if: steps.versions.outputs.new-release-version-exists == '1'
      run: perl -pe "s/^VERSION_NAME=.*/VERSION_NAME=${{ steps.versions.outputs.release-version }}/g" -i $BASEDIR/gradle.properties
    - name: "Publish"
      run: |
        ./gradlew publish
        echo "$(cat $BASEDIR/gradle.properties | grep VERSION_NAME | cut -d'=' -f2) deployed!"
