# This is separated by library because of a limit with GitHub and Bintray about the number of published artifacts.
name: "Publish Arrow Fx"

on:
  push:
    branches:
    - master
    paths:
    - 'gradle.properties'
    - '**.gradle'
    - 'scripts/**'

jobs:
  publish-arrow-fx:

    env:
      BASEDIR: ${{github.workspace}}/..
      JAVA_OPTS: -Xms512m -Xmx1024m
      ARROW_LIB: arrow-fx

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: "Get target: OSS or Bintray"
      id: versions
      run: |
        LATEST_PUBLISHED_VERSION=$(curl -X GET https://api.bintray.com/packages/arrow-kt/arrow-kt/arrow/versions/_latest | jq -r '.name')
        LATEST_VERSION=$(grep LATEST_VERSION gradle.properties | cut -d= -f2)
        SNAPSHOT_VERSION=$(grep VERSION_NAME gradle.properties | cut -d= -f2)
        NEW_VERSION_EXISTS=$([ "$LATEST_PUBLISHED_VERSION" == "$LATEST_VERSION" ] && echo '0' || echo '1')
        echo "::set-output name=latest-published-version::$LATEST_PUBLISHED_VERSION"
        echo "::set-output name=release-version::$LATEST_VERSION"
        echo "::set-output name=snapshot-version::$SNAPSHOT_VERSION"
        echo "::set-output name=new-version-exists::$NEW_VERSION_EXISTS"
    - name: "Publish into OSS"
      if: steps.versions.outputs.new-version-exists == '0'
      env:
        BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
        BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
      run: |
        git clone https://github.com/arrow-kt/$ARROW_LIB.git $BASEDIR/$ARROW_LIB
        $BASEDIR/arrow/scripts/project-publish.sh $ARROW_LIB
    - name: Publish into Bintray
      if: steps.versions.outputs.new-version-exists == '1'
      env:
        BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
        BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
      run: |
        echo "Update version ..."
        perl -pe "s/^VERSION_NAME=.*/VERSION_NAME=${{ steps.versions.outputs.release-version }}/g" -i gradle.properties
        $BASEDIR/arrow/scripts/lib-publish.sh $ARROW_LIB
    - name: Create tag
      if: steps.versions.outputs.new-version-exists == '1'
      env:
        GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
      run: |
        cd $BASEDIR/$ARROW_LIB
        git remote set-url origin https://arrow-kt:$GITHUB_TOKEN@github.com/arrow-kt/$ARROW_LIB.git
        git config --global user.email "arrow-kt@users.noreply.github.com"
        git config --global user.name "arrow-kt"
        git tag -a ${{ steps.versions.outputs.release-version }} -m "Release ${{ steps.versions.outputs.release-version }}"
        git push origin ${{ steps.versions.outputs.release-version }}
    - name: Create release notes
      if: steps.versions.outputs.new-version-exists == '1'
      env:
        GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
      run: |
        export LATEST_PUBLISHED_VERSION=${{ steps.versions.outputs.latest-published-version }}
        export RELEASE_VERSION=${{ steps.versions.outputs.release-version }}
        $BASEDIR/arrow/scripts/create-release-notes.sh
