name: "Run Gradle tasks"

on:
  pull_request:
    paths:
    - 'gradle.properties'
    - 'gradle/**'
    - 'scripts/**'
    - 'lists/**'

jobs:
  run-tasks:

    env:
      BASEDIR: ${{github.workspace}}/..
      JAVA_OPTS: -Xms512m -Xmx1024m

    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
    - uses: actions/checkout@v2
    - name: Prepare env
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        perl -pe "s/git\@github.com:/https:\/\/github.com\//g" -i scripts/commons4gradle.sh
        . $BASEDIR/arrow/scripts/commons4gradle.sh
        BRANCH_NAME=${{ github.event.pull_request.head.ref }}
        sleep 180
        for repository in $(cat $BASEDIR/arrow/lists/libs.txt); do
            checkAndDownloadViaHTTPS $repository $BRANCH_NAME
            replaceGlobalPropertiesbyLocalConf $BASEDIR/$repository/gradle.properties
        done
    - name: Build with local dependencies
      run: |
        cd $BASEDIR/arrow-core
        ./gradlew buildWithLocalDeps
    - name: Build Doc with local dependencies
      run: |
        cd $BASEDIR/arrow-core
        ./gradlew buildArrowDocWithLocalDeps
